# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g36mk8BBmoCxMHd7V7R-5EhSK_B07F0L
"""

import pandas as pd

diabetes = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_DataSci_507/main/Datasets/Diabetes/DB1_Diabetes/diabetic_data.csv')

##### T-test
from scipy.stats import ttest_ind

#is there a difference between sex (M:F) (IV)
#and the number of days in hospital?

Female = diabetes[diabetes['gender']=='Female']
Male = diabetes[diabetes['gender']=='Male']
ttest_ind(Female['time_in_hospital'], Male['time_in_hospital'])
#there is no difference between sex and the number of days in hospital, because pvalue > 0.05

#is there a difference between RACE (Caucasian and African American)
#and the number of days in hospital?

Caucasian = diabetes[diabetes['race']=='Caucasian']
AfricanAmerican = diabetes[diabetes['race']=='AfricanAmerican']
ttest_ind(Caucasian['time_in_hospital'], AfricanAmerican['time_in_hospital'])
#there is no difference between Race(Caucasian and African American) and the number of days in hospital, because pvalue > 0.05

#is there a difference between RACE (Asian and African American)
#and the number of lab procedures performed?

Asian = diabetes[diabetes['race']=='Asian']
AfricanAmerican = diabetes[diabetes['race']=='AfricanAmerican']
ttest_ind(Asian['num_lab_procedures'], AfricanAmerican['num_lab_procedures'])
#there is no difference between Race (Asian and African American) and the number of lab procedures performed, because pvalue > 0.05